<a href="https://colab.research.google.com/github/DABallentine/knowledge_discovery_charlotte/blob/main/Jupiter%20Notebooks/Census_Data_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## This Notebook modifies the census dataset to prepare it to merge with the 311-Service Requests dataset

Census data was taken from <a href="https://data.census.gov/cedsci/table?d=ACS%205-Year%20Estimates%20Data%20Profiles&hidePreview=false&vintage=2018&layer=zcta5&tid=ACSDP5Y2019.DP03">the datasets of census.gov</a>. This data set is a collection of household income statistics, Employment statistics, Details about Families and Non-families, People under poverty line and People commuting to work.

In [1]:
# Import necessary packages
import pandas as pd
import numpy as np

In [2]:
# Function to read data from URL
def read_data_from_URL(url):
    df=pd.read_csv(url)
    return df

In [3]:
#importing census economic dataset which contains household income and age data
census_economic_url='https://bitbucket.org/nthammad-uncc/knowledge_discovery_charlotte/raw/3f5574c9648a95b7d760bb2f27e879dcaa78b00a/data/CENSUS_ECONOMIC_2016_2019.csv'
census_df = read_data_from_URL(census_economic_url)
print("Records:", census_df.shape[0], "\nFeatures:", census_df.shape[1])

Records: 932
Features: 551

In [4]:
census_df.head()

,YEAR,id,Geographic Area Name,Estimate!!EMPLOYMENT STATUS!!Population 16 years and over,Margin of Error!!EMPLOYMENT STATUS!!Population 16 years and over,Percent!!EMPLOYMENT STATUS!!Population 16 years and over,Percent Margin of Error!!EMPLOYMENT STATUS!!Population 16 years and over,Estimate!!EMPLOYMENT STATUS!!Population 16 years and over!!In labor force,Margin of Error!!EMPLOYMENT STATUS!!Population 16 years and over!!In labor force,Percent!!EMPLOYMENT STATUS!!Population 16 years and over!!In labor force,...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!18 years and over!!65 years and over,Percent Margin of Error!!PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!18 years and over!!65 years and over,Estimate!!PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!People in families,Margin of Error!!PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!People in families,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!People in families,Percent Margin of Error!!PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!People in families,Estimate!!PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!Unrelated individuals 15 years and over,Margin of Error!!PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!Unrelated individuals 15 years and over,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!Unrelated individuals 15 years and over,Percent Margin of Error!!PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!Unrelated individuals 15 years and over
0,2016,1400000US37119000100,"Census Tract 1, Mecklenburg County, North Caro...",4816,395,4816,(X),3969,369,82.4,...,9.7,10.9,(X),(X),0,2.6,(X),(X),12.8,6.1
1,2016,1400000US37119000300,"Census Tract 3, Mecklenburg County, North Caro...",627,80,627,(X),415,76,66.2,...,50,38.6,(X),(X),3.4,11.9,(X),(X),44,8.4
2,2016,1400000US37119000400,"Census Tract 4, Mecklenburg County, North Caro...",2588,194,2588,(X),2300,193,88.9,...,39,33.1,(X),(X),13.1,13.4,(X),(X),14.5,5.3
3,2016,1400000US37119000500,"Census Tract 5, Mecklenburg County, North Caro...",4590,350,4590,(X),3765,320,82,...,52.7,24.8,(X),(X),4.8,6,(X),(X),18,6.3
4,2016,1400000US37119000600,"Census Tract 6, Mecklenburg County, North Caro...",2487,218,2487,(X),2094,198,84.2,...,51.6,27.9,(X),(X),18,9.5,(X),(X),18.9,7.3

## Converting feature names from Census data to better format and removing unnecessary features

In [5]:
# Function to update column names of the census dataset
# Census data set has column names that follow the format:
## 'Estimate!!EMPLOYMENT STATUS!!Population 16 years and over'
## 'Margin of Error!!EMPLOYMENT STATUS!!Population 16 years and over'
## 'Percent!!EMPLOYMENT STATUS!!Population 16 years and over'
## 'Percent Margin of Error!!EMPLOYMENT STATUS!!Population 16 years and over'

# There are also lot of nested details in the column names like: 
## 'Estimate!!EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Armed Forces'

# This function updates the Estimate columns in the format:
## EMPLOYMENT STATUS_Population 16 years and over --> removing "Estimate" and including underscore
## Margin of Error_EMPLOYMENT STATUS_Population 16 years and over --> including underscores
## Percent_EMPLOYMENT STATUS_Population 16 years and over --> including underscores
## Percent Margin of Error_EMPLOYMENT STATUS_Population 16 years and over --> including underscores

## [check if it makes sense] EMPLOYMENT STATUS_Population 16 years and over_Armed Forces --> removing unnecessary nesting "Armed Forces"

# The columns starting with "Margin of Error", "Percent" and "Percent Margin of Error" will be dropped later

def rename_census_column(df):
    col_dict={}
    for col_name in df.columns.values.tolist():
        col_split=col_name.split('!!')
        if len(col_split) == 1:
            if col_split[0] == 'id':
                col_dict[col_name]='GEO_ID'
            else:
                col_dict[col_name]=col_name
        elif len(col_split) >=3:
            if col_split[0] == 'Estimate':
                col_dict[col_name]='_'.join(col_split[1:])
            else:
                col_dict[col_name]='_'.join(col_split)
        
    df.rename(col_dict, axis=1, inplace=True)

In [6]:
rename_census_column(census_df)

In [7]:
# This is a list of some unneccessary Estimate columns that need to be dropped
lst_other_col_names=['Geographic Area Name','EMPLOYMENT STATUS_Population 16 years and over_In labor force_Civilian labor force',
                        'COMMUTING TO WORK_Mean travel time to work (minutes)',
                        'EMPLOYMENT STATUS_Population 16 years and over_In labor force_Civilian labor force_Employed',
                        'EMPLOYMENT STATUS_Population 16 years and over_In labor force_Civilian labor force_Unemployed',
                        'EMPLOYMENT STATUS_Population 16 years and over_In labor force_Armed Forces',
                        'EMPLOYMENT STATUS_Civilian labor force',
                        'EMPLOYMENT STATUS_Civilian labor force_Unemployment Rate',
                        'EMPLOYMENT STATUS_Females 16 years and over_In labor force',
                        'EMPLOYMENT STATUS_Females 16 years and over_In labor force_Civilian labor force',
                        'EMPLOYMENT STATUS_Females 16 years and over_In labor force_Civilian labor force_Employed',
                        'EMPLOYMENT STATUS_Own children of the householder under 6 years_All parents in family in labor force',
                        'EMPLOYMENT STATUS_Own children of the householder 6 to 17 years_All parents in family in labor force',
                        'COMMUTING TO WORK_Mean travel time to work (minutes)',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With earnings',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With earnings_Mean earnings (dollars)',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With Social Security',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With Social Security_Mean Social Security income (dollars)',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With retirement income',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With retirement income_Mean retirement income (dollars)',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With Supplemental Security Income',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With Supplemental Security Income_Mean Supplemental Security Income (dollars)',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With cash public assistance income',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With cash public assistance income_Mean cash public assistance income (dollars)',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With Food Stamp/SNAP benefits in the past 12 months',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Families',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Families_Less than $10,000',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Families_$10,000 to $14,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Families_$15,000 to $24,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Families_$25,000 to $34,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Families_$35,000 to $49,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Families_$50,000 to $74,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Families_$75,000 to $99,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Families_$100,000 to $149,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Families_$150,000 to $199,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Families_$200,000 or more',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Families_Median family income (dollars)',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Families_Mean family income (dollars)',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Nonfamily households',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Nonfamily households_Median nonfamily income (dollars)',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Nonfamily households_Mean nonfamily income (dollars)',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Median earnings for male full-time, year-round workers (dollars)',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Median earnings for female full-time, year-round workers (dollars)',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population_With health insurance coverage_With private health insurance',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population_With health insurance coverage_With public coverage',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population under 18 years',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population under 18 years_No health insurance coverage',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_In labor force',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_In labor force_Employed',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_In labor force_Employed_With health insurance coverage',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_In labor force_Employed_With health insurance coverage_With private health insurance',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_In labor force_Employed_With health insurance coverage_With public coverage',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_In labor force_Employed_No health insurance coverage',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_In labor force_Unemployed',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_In labor force_Unemployed_With health insurance coverage',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_In labor force_Unemployed_With health insurance coverage_With private health insurance',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_In labor force_Unemployed_With health insurance coverage_With public coverage',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_In labor force_Unemployed_No health insurance coverage',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_Not in labor force',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_Not in labor force_With health insurance coverage',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_Not in labor force_With health insurance coverage_With private health insurance',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_Not in labor force_With health insurance coverage_With public coverage',
                        'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population 18 to 64 years_Not in labor force_No health insurance coverage',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All families_With related children of the householder under 18 years',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All families_With related children of the householder under 18 years_With related children of the householder under 5 years only',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_Married couple families',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_Married couple families_With related children of the householder under 18 years',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_Married couple families_With related children of the householder under 18 years_With related children of the householder under 5 years only',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_Families with female householder, no husband present',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_Families with female householder, no husband present_With related children of the householder under 18 years',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_Families with female householder, no husband present_With related children of the householder under 18 years_With related children of the householder under 5 years only',          
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_Under 18 years_Related children of the householder under 18 years',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_Under 18 years_Related children of the householder under 18 years_Related children of the householder under 5 years',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_Under 18 years_Related children of the householder under 18 years_Related children of the householder 5 to 17 years',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over_18 to 64 years',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over_65 years and over',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All families',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_Under 18 years',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_People in families',
                        'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_Unrelated individuals 15 years and over'
                        ]

In [8]:
# Function to remove unnecessary features in census data
def drop_census_cols(df):
    drop_col_list=[]
    drop_df=df.copy(deep=True)
    lst_first_words=['Margin of Error','Percent','Percent Margin of Error','OCCUPATION','INDUSTRY','CLASS OF WORKER']
    lst_percent_exceptions = ['Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over_18 to 64 years',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over_65 years and over',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_People in families',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_Unrelated individuals 15 years and over']
    for col_name in drop_df.columns.values.tolist():
        col_split=col_name.split('_')
        if len(col_split)>1 :
            if col_split[0] in lst_first_words and col_name not in lst_percent_exceptions:
                drop_col_list.append(col_name)        
        
        if col_name in lst_other_col_names:
            drop_col_list.append(col_name)
    
    drop_df.drop(drop_col_list, axis=1, inplace=True)
    return drop_df

In [9]:
dropped_census_df=drop_census_cols(census_df)
print("Original Census :::\nRecords:", census_df.shape[0], "\nFeatures:", census_df.shape[1])
print("Dropped Census :::\nRecords:", dropped_census_df.shape[0], "\nFeatures:", dropped_census_df.shape[1])

Original Census :::
Records: 932
Features: 551
Dropped Census :::
Records: 932
Features: 37

In [10]:
dropped_census_df.columns.values

array(['YEAR', 'GEO_ID', 'EMPLOYMENT STATUS_Population 16 years and over',
       'EMPLOYMENT STATUS_Population 16 years and over_In labor force',
       'EMPLOYMENT STATUS_Population 16 years and over_Not in labor force',
       'EMPLOYMENT STATUS_Females 16 years and over',
       'EMPLOYMENT STATUS_Own children of the householder under 6 years',
       'EMPLOYMENT STATUS_Own children of the householder 6 to 17 years',
       'COMMUTING TO WORK_Workers 16 years and over',
       'COMMUTING TO WORK_Workers 16 years and over_Car, truck, or van -- drove alone',
       'COMMUTING TO WORK_Workers 16 years and over_Car, truck, or van -- carpooled',
       'COMMUTING TO WORK_Workers 16 years and over_Public transportation (excluding taxicab)',
       'COMMUTING TO WORK_Workers 16 years and over_Walked',
       'COMMUTING TO WORK_Workers 16 years and over_Other means',
       'COMMUTING TO WORK_Workers 16 years and over_Worked at home',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Less than $10,000',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$10,000 to $14,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$15,000 to $24,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$25,000 to $34,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$35,000 to $49,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$50,000 to $74,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$75,000 to $99,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$100,000 to $149,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$150,000 to $199,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$200,000 or more',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Median household income (dollars)',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Mean household income (dollars)',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Per capita income (dollars)',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Median earnings for workers (dollars)',
       'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population_With health insurance coverage',
       'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population_No health insurance coverage',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over_18 to 64 years',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over_65 years and over',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_People in families',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_Unrelated individuals 15 years and over'],
      dtype=object)

## Transforming census data GEO_ID column, renaming columns

In [11]:
# GEO_ID column of the census data is in the form 1400000US37119000100
# This function transforms the column to only store the census tract id which is 37119000100
# This id will then be used to join the census data with zip codes

def transform_census_geo_id(geoid):
    if 'US' in str(geoid):
        return int(geoid.split('US')[1])
    else:
        return int(geoid)

In [12]:
dropped_census_df['GEO_ID'] = dropped_census_df['GEO_ID'].apply(lambda x: transform_census_geo_id(x))
dropped_census_df['GEO_ID'].head(5)

0    37119000100
1    37119000300
2    37119000400
3    37119000500
4    37119000600
Name: GEO_ID, dtype: int64

In [13]:
dropped_census_df.dtypes

YEAR                                                                                                                                                       int64
GEO_ID                                                                                                                                                     int64
EMPLOYMENT STATUS_Population 16 years and over                                                                                                             int64
EMPLOYMENT STATUS_Population 16 years and over_In labor force                                                                                              int64
EMPLOYMENT STATUS_Population 16 years and over_Not in labor force                                                                                          int64
EMPLOYMENT STATUS_Females 16 years and over                                                                                                                int64
EMPLOYMENT STATUS_Own children of the householder under 6 years                                                                                            int64
EMPLOYMENT STATUS_Own children of the householder 6 to 17 years                                                                                            int64
COMMUTING TO WORK_Workers 16 years and over                                                                                                                int64
COMMUTING TO WORK_Workers 16 years and over_Car, truck, or van -- drove alone                                                                              int64
COMMUTING TO WORK_Workers 16 years and over_Car, truck, or van -- carpooled                                                                                int64
COMMUTING TO WORK_Workers 16 years and over_Public transportation (excluding taxicab)                                                                      int64
COMMUTING TO WORK_Workers 16 years and over_Walked                                                                                                         int64
COMMUTING TO WORK_Workers 16 years and over_Other means                                                                                                    int64
COMMUTING TO WORK_Workers 16 years and over_Worked at home                                                                                                 int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households                                                                                  int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Less than $10,000                                                                int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$10,000 to $14,999                                                               int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$15,000 to $24,999                                                               int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$25,000 to $34,999                                                               int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$35,000 to $49,999                                                               int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$50,000 to $74,999                                                               int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$75,000 to $99,999                                                               int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$100,000 to $149,999                                                             int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$150,000 to $199,999                                                             int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$200,000 or more                                                                 int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Median household income (dollars)                                               object
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Mean household income (dollars)                                                 object
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Per capita income (dollars)                                                                      object
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Median earnings for workers (dollars)                                                            object
HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population_With health insurance coverage                                                          int64
HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population_No health insurance coverage                                                            int64
Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over                      object
Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over_18 to 64 years       object
Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over_65 years and over    object
Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_People in families                                object
Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_Unrelated individuals 15 years and over           object
dtype: object

In [14]:
def replace_nan_census_df(df):
    #some of the census data columns had '-','N' in place of NaN, and one column had '250,000+' which is replaced to 250000
    df[df.columns.drop(['YEAR','GEO_ID'])] = df[df.columns.drop(['YEAR','GEO_ID'])].replace('-', np.nan)
    df[df.columns.drop(['YEAR','GEO_ID'])] = df[df.columns.drop(['YEAR','GEO_ID'])].replace('N', np.nan)
    df[df.columns.drop(['YEAR','GEO_ID'])] = df[df.columns.drop(['YEAR','GEO_ID'])].replace('250,000+', 250000)
    for col_name in df.columns.values.tolist():
        if col_name != 'YEAR' and col_name != 'GEO_ID':
            df[col_name] = pd.to_numeric(df[col_name])

In [15]:
replace_nan_census_df(dropped_census_df)

In [16]:
dropped_census_df.dtypes

YEAR                                                                                                                                                        int64
GEO_ID                                                                                                                                                      int64
EMPLOYMENT STATUS_Population 16 years and over                                                                                                              int64
EMPLOYMENT STATUS_Population 16 years and over_In labor force                                                                                               int64
EMPLOYMENT STATUS_Population 16 years and over_Not in labor force                                                                                           int64
EMPLOYMENT STATUS_Females 16 years and over                                                                                                                 int64
EMPLOYMENT STATUS_Own children of the householder under 6 years                                                                                             int64
EMPLOYMENT STATUS_Own children of the householder 6 to 17 years                                                                                             int64
COMMUTING TO WORK_Workers 16 years and over                                                                                                                 int64
COMMUTING TO WORK_Workers 16 years and over_Car, truck, or van -- drove alone                                                                               int64
COMMUTING TO WORK_Workers 16 years and over_Car, truck, or van -- carpooled                                                                                 int64
COMMUTING TO WORK_Workers 16 years and over_Public transportation (excluding taxicab)                                                                       int64
COMMUTING TO WORK_Workers 16 years and over_Walked                                                                                                          int64
COMMUTING TO WORK_Workers 16 years and over_Other means                                                                                                     int64
COMMUTING TO WORK_Workers 16 years and over_Worked at home                                                                                                  int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households                                                                                   int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Less than $10,000                                                                 int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$10,000 to $14,999                                                                int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$15,000 to $24,999                                                                int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$25,000 to $34,999                                                                int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$35,000 to $49,999                                                                int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$50,000 to $74,999                                                                int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$75,000 to $99,999                                                                int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$100,000 to $149,999                                                              int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$150,000 to $199,999                                                              int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$200,000 or more                                                                  int64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Median household income (dollars)                                               float64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Mean household income (dollars)                                                 float64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Per capita income (dollars)                                                                      float64
INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Median earnings for workers (dollars)                                                            float64
HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population_With health insurance coverage                                                           int64
HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population_No health insurance coverage                                                             int64
Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over                      float64
Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over_18 to 64 years       float64
Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over_65 years and over    float64
Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_People in families                                float64
Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_Unrelated individuals 15 years and over           float64
dtype: object

In [17]:
#rename the columns in the census data
rename_col_dict={'EMPLOYMENT STATUS_Population 16 years and over':'EMPLOYED_All',
       'EMPLOYMENT STATUS_Population 16 years and over_In labor force':'EMPLOYED_In labor force',
       'EMPLOYMENT STATUS_Population 16 years and over_Not in labor force':'EMPLOYED_Other',
       'EMPLOYMENT STATUS_Females 16 years and over':'EMPLOYED_Female Only',
       'EMPLOYMENT STATUS_Own children of the householder under 6 years':'EMPLOYED_Householder with children under 6 years',
       'EMPLOYMENT STATUS_Own children of the householder 6 to 17 years':'EMPLOYED_Householder with children between 6 to 17 years',
       'COMMUTING TO WORK_Workers 16 years and over':'COMMUTING TO WORK_All',
       'COMMUTING TO WORK_Workers 16 years and over_Car, truck, or van -- drove alone':'COMMUTING TO WORK_Alone in car',
       'COMMUTING TO WORK_Workers 16 years and over_Car, truck, or van -- carpooled':'COMMUTING TO WORK_Carpool',
       'COMMUTING TO WORK_Workers 16 years and over_Public transportation (excluding taxicab)':'COMMUTING TO WORK_Public transportation',
       'COMMUTING TO WORK_Workers 16 years and over_Walked':'COMMUTING TO WORK_Walk',
       'COMMUTING TO WORK_Workers 16 years and over_Other means':'COMMUTING TO WORK_Other',
       'COMMUTING TO WORK_Workers 16 years and over_Worked at home':'COMMUTING TO WORK_Worked at home',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households':'INCOME AND BENEFITS_Total households',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Median household income (dollars)':'INCOME AND BENEFITS_Median households income (dollars)',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Mean household income (dollars)':'INCOME AND BENEFITS_Mean households income (dollars)',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With retirement income':'INCOME AND BENEFITS_Retired householders',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With cash public assistance income':'INCOME AND BENEFITS_Households with public assistance income',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_With Food Stamp/SNAP benefits in the past 12 months':'INCOME AND BENEFITS_Households with Food Stamp/SNAP benefits in the past 1 year',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Per capita income (dollars)':'INCOME AND BENEFITS_Per capita Income',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Median earnings for workers (dollars)':'INCOME AND BENEFITS_Median earnings for workers (dollars)',
       'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population_With health insurance coverage':'Civilian Population_With health insurance coverage',
       'HEALTH INSURANCE COVERAGE_Civilian noninstitutionalized population_No health insurance coverage':'Civilian Population_No health insurance coverage',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over':'PERCENTAGE BELOW POVERTY LEVEL_All',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over_18 to 64 years':'PERCENTAGE BELOW POVERTY LEVEL_18 to 64 years',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_All people_18 years and over_65 years and over':'PERCENTAGE BELOW POVERTY LEVEL_65 years and over',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_People in families':'PERCENTAGE BELOW POVERTY LEVEL_Families',
       'Percent_PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL_Unrelated individuals 15 years and over':'PERCENTAGE BELOW POVERTY LEVEL_Unrelated individuals 15 years and over'}

dropped_census_df.rename(rename_col_dict, axis=1, inplace=True)

In [18]:
dropped_census_df.columns.values

array(['YEAR', 'GEO_ID', 'EMPLOYED_All', 'EMPLOYED_In labor force',
       'EMPLOYED_Other', 'EMPLOYED_Female Only',
       'EMPLOYED_Householder with children under 6 years',
       'EMPLOYED_Householder with children between 6 to 17 years',
       'COMMUTING TO WORK_All', 'COMMUTING TO WORK_Alone in car',
       'COMMUTING TO WORK_Carpool',
       'COMMUTING TO WORK_Public transportation',
       'COMMUTING TO WORK_Walk', 'COMMUTING TO WORK_Other',
       'COMMUTING TO WORK_Worked at home',
       'INCOME AND BENEFITS_Total households',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Less than $10,000',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$10,000 to $14,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$15,000 to $24,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$25,000 to $34,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$35,000 to $49,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$50,000 to $74,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$75,000 to $99,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$100,000 to $149,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$150,000 to $199,999',
       'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$200,000 or more',
       'INCOME AND BENEFITS_Median households income (dollars)',
       'INCOME AND BENEFITS_Mean households income (dollars)',
       'INCOME AND BENEFITS_Per capita Income',
       'INCOME AND BENEFITS_Median earnings for workers (dollars)',
       'Civilian Population_With health insurance coverage',
       'Civilian Population_No health insurance coverage',
       'PERCENTAGE BELOW POVERTY LEVEL_All',
       'PERCENTAGE BELOW POVERTY LEVEL_18 to 64 years',
       'PERCENTAGE BELOW POVERTY LEVEL_65 years and over',
       'PERCENTAGE BELOW POVERTY LEVEL_Families',
       'PERCENTAGE BELOW POVERTY LEVEL_Unrelated individuals 15 years and over'],
      dtype=object)

In [19]:
#add necessary columns and drop the repetitive up columns
dropped_census_df['INCOME AND BENEFITS_Lower Income Households']=dropped_census_df['INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Less than $10,000']+dropped_census_df['INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$10,000 to $14,999']+dropped_census_df['INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$15,000 to $24,999']+dropped_census_df['INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$25,000 to $34,999']              
dropped_census_df['INCOME AND BENEFITS_Mid Income Households']=dropped_census_df['INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$35,000 to $49,999']+dropped_census_df['INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$50,000 to $74,999']+dropped_census_df['INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$75,000 to $99,999']+dropped_census_df['INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$100,000 to $149,999']
dropped_census_df['INCOME AND BENEFITS_Higher Income Households']=dropped_census_df['INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$150,000 to $199,999']+dropped_census_df['INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$200,000 or more']
dropped_census_df['COMMUTING TO WORK_By Car']=dropped_census_df['COMMUTING TO WORK_Alone in car']+dropped_census_df['COMMUTING TO WORK_Carpool']
dropped_census_df.drop(['INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_Less than $10,000',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$10,000 to $14,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$15,000 to $24,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$25,000 to $34,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$35,000 to $49,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$50,000 to $74,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$75,000 to $99,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$100,000 to $149,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$150,000 to $199,999',
                        'INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS)_Total households_$200,000 or more',
                        'COMMUTING TO WORK_Alone in car',
                        'COMMUTING TO WORK_Carpool'], axis=1, inplace=True)

In [20]:
#reorder the columns
dropped_census_df = dropped_census_df.iloc[:,[0,1,2,3,4,5,6,7,8,28,9,10,11,12,13,25,26,27,14,15,16,17,18,19,20,21,22,23,24]]

In [21]:
dropped_census_df.head()

,YEAR,GEO_ID,EMPLOYED_All,EMPLOYED_In labor force,EMPLOYED_Other,EMPLOYED_Female Only,EMPLOYED_Householder with children under 6 years,EMPLOYED_Householder with children between 6 to 17 years,COMMUTING TO WORK_All,COMMUTING TO WORK_By Car,...,INCOME AND BENEFITS_Mean households income (dollars),INCOME AND BENEFITS_Per capita Income,INCOME AND BENEFITS_Median earnings for workers (dollars),Civilian Population_With health insurance coverage,Civilian Population_No health insurance coverage,PERCENTAGE BELOW POVERTY LEVEL_All,PERCENTAGE BELOW POVERTY LEVEL_18 to 64 years,PERCENTAGE BELOW POVERTY LEVEL_65 years and over,PERCENTAGE BELOW POVERTY LEVEL_Families,PERCENTAGE BELOW POVERTY LEVEL_Unrelated individuals 15 years and over
0,2016,37119000100,4816,3969,847,1926,71,29,3802,1769,...,141380.0,85157.0,68750.0,4694,237,9.1,9.0,9.7,0.0,12.8
1,2016,37119000300,627,415,212,294,7,11,375,313,...,88033.0,65941.0,61563.0,621,19,33.0,31.7,50.0,3.4,44.0
2,2016,37119000400,2588,2300,288,1134,20,32,2251,1399,...,90460.0,63515.0,64744.0,2499,141,14.5,13.3,39.0,13.1,14.5
3,2016,37119000500,4590,3765,825,2058,192,235,3437,2083,...,93399.0,49081.0,45122.0,4391,545,14.6,11.9,52.7,4.8,18.0
4,2016,37119000600,2487,2094,393,1256,230,162,1961,1258,...,78462.0,44427.0,42172.0,2553,225,15.4,13.4,51.6,18.0,18.9

## Importing Zip code to Census Tract conversion dataset

The source of Census Tract Id to Zip code conversion has been taken from <a href="https://www.huduser.gov/portal/datasets/usps_crosswalk.html#data">the dataset portal of huduser.gov</a>. This conversion is necessary to link the census data to 311-Service Requests data through zip code.

In [22]:
#importing census tract and zip code mapping dataset
census_tract_url='https://bitbucket.org/nthammad-uncc/knowledge_discovery_charlotte/raw/3f5574c9648a95b7d760bb2f27e879dcaa78b00a/data/Zip_to_Census_Track.csv'
census_tract_df = read_data_from_URL(census_tract_url)
census_tract_df.head()

,ZIP,TRACT,USPS_ZIP_PREF_CITY,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
0,27006,37059080200,ADVANCE,0.224640,0.190157,0.483516,0.225580
1,27006,37059080300,ADVANCE,0.577647,0.704698,0.516484,0.583554
2,27006,37059080400,ADVANCE,0.197713,0.105145,0.000000,0.190866
3,27007,37171931102,ARARAT,0.249526,0.344828,0.000000,0.252078
4,27007,37171931101,ARARAT,0.722960,0.551724,0.000000,0.718375

In [23]:
# drop unnecessary column
census_tract_df.drop('USPS_ZIP_PREF_CITY', axis=1, inplace=True)

# rename TRACT to GEO ID and ZIP to ZIP_CODE   
census_tract_df.rename({"TRACT":"GEO_ID", "ZIP": "ZIP_CODE"}, axis=1, inplace=True)

census_tract_df.head()

   ZIP_CODE       GEO_ID  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
0     27006  37059080200   0.224640   0.190157   0.483516   0.225580
1     27006  37059080300   0.577647   0.704698   0.516484   0.583554
2     27006  37059080400   0.197713   0.105145   0.000000   0.190866
3     27007  37171931102   0.249526   0.344828   0.000000   0.252078
4     27007  37171931101   0.722960   0.551724   0.000000   0.718375

In [24]:
print("Census Tract :::\nRecords:", census_tract_df.shape[0], "\nFeatures:", census_tract_df.shape[1])

Census Tract :::
Records: 5301
Features: 6

## Merge Census data with zip code

In [25]:
# Each GEO ID can be associated to multiple zip codes and some zip codes can be associated to multiple GEO IDs
# pandas merge ensures each of the GEO IDs are mapped to each zip code and vice-versa
# this might duplicate the data but there is no loss of it
merged_census_df = pd.merge(dropped_census_df, census_tract_df, 
                   on='GEO_ID', 
                   how='left')
merged_census_df.head()

,YEAR,GEO_ID,EMPLOYED_All,EMPLOYED_In labor force,EMPLOYED_Other,EMPLOYED_Female Only,EMPLOYED_Householder with children under 6 years,EMPLOYED_Householder with children between 6 to 17 years,COMMUTING TO WORK_All,COMMUTING TO WORK_By Car,...,PERCENTAGE BELOW POVERTY LEVEL_All,PERCENTAGE BELOW POVERTY LEVEL_18 to 64 years,PERCENTAGE BELOW POVERTY LEVEL_65 years and over,PERCENTAGE BELOW POVERTY LEVEL_Families,PERCENTAGE BELOW POVERTY LEVEL_Unrelated individuals 15 years and over,ZIP_CODE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
0,2016,37119000100,4816,3969,847,1926,71,29,3802,1769,...,9.1,9.0,9.7,0.0,12.8,28201,0.000000,1.000000,0.000000,1.000000
1,2016,37119000100,4816,3969,847,1926,71,29,3802,1769,...,9.1,9.0,9.7,0.0,12.8,28202,0.484598,0.693141,0.316558,0.500457
2,2016,37119000100,4816,3969,847,1926,71,29,3802,1769,...,9.1,9.0,9.7,0.0,12.8,28203,0.000241,0.027871,0.009434,0.004006
3,2016,37119000100,4816,3969,847,1926,71,29,3802,1769,...,9.1,9.0,9.7,0.0,12.8,28244,0.000000,1.000000,1.000000,1.000000
4,2016,37119000100,4816,3969,847,1926,71,29,3802,1769,...,9.1,9.0,9.7,0.0,12.8,28246,0.000000,1.000000,1.000000,1.000000

In [26]:
print("Merged Census :::\nRecords:", merged_census_df.shape[0], "\nFeatures:", merged_census_df.shape[1])

Merged Census :::
Records: 1748
Features: 34

In [27]:
# since ZIP_CODE to GEO_ID is a many to many relationship, we will be calculating the mean of all census column values
# based on the grouping by ZIP_CODE and YEAR
mean_cols_list=merged_census_df[merged_census_df.columns.drop(['YEAR','GEO_ID','ZIP_CODE'])].columns.values.tolist()
dict_mean_cols={}
for colname in mean_cols_list:
    dict_mean_cols[colname]=['mean']

# append the YEAR AND ZIP_CODE columns to the mean_cols_list to rename after the aggregation
mean_cols_list.insert(0,'ZIP_CODE')
mean_cols_list.insert(0,'YEAR')
mean_census_df=merged_census_df.groupby(['YEAR','ZIP_CODE']).agg(dict_mean_cols).reset_index()
mean_census_df.columns=mean_cols_list
mean_census_df.head()

,YEAR,ZIP_CODE,EMPLOYED_All,EMPLOYED_In labor force,EMPLOYED_Other,EMPLOYED_Female Only,EMPLOYED_Householder with children under 6 years,EMPLOYED_Householder with children between 6 to 17 years,COMMUTING TO WORK_All,COMMUTING TO WORK_By Car,...,Civilian Population_No health insurance coverage,PERCENTAGE BELOW POVERTY LEVEL_All,PERCENTAGE BELOW POVERTY LEVEL_18 to 64 years,PERCENTAGE BELOW POVERTY LEVEL_65 years and over,PERCENTAGE BELOW POVERTY LEVEL_Families,PERCENTAGE BELOW POVERTY LEVEL_Unrelated individuals 15 years and over,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
0,2016,28027,4988.000,3737.000,1251.00,2499.00,532.00,1388.000,3491.00,2958.000,...,626.00,6.4000,6.400,6.600,5.7000,13.8000,0.000118,0.000000,0.000000,0.000107
1,2016,28031,3997.875,2794.625,1203.25,2080.00,270.50,833.625,2594.75,2143.375,...,308.00,5.2375,5.775,2.400,3.2625,13.4875,0.125000,0.125000,0.125000,0.125000
2,2016,28036,4038.500,2635.250,1403.25,2044.75,273.25,898.750,2445.00,1880.750,...,352.75,5.6250,6.575,1.975,2.4500,16.9750,0.203848,0.233013,0.242898,0.206449
3,2016,28070,3980.000,2891.000,1089.00,1927.00,559.00,1061.000,2683.00,2358.000,...,300.00,7.7000,8.900,0.000,5.0000,26.8000,1.000000,1.000000,1.000000,1.000000
4,2016,28078,3609.150,2670.300,938.85,1868.90,422.95,849.400,2463.90,2156.900,...,351.40,4.8550,4.860,4.175,3.4250,14.4550,0.047598,0.049680,0.049846,0.047767

In [28]:
#save the final census datafile into a csv for future purposes
mean_census_df.to_csv('../Data/final_census_data.csv', encoding='utf-8')